### ISSUE TITLE
cfd

### ISSUE THREAD

**Issue by aobama-mac** [Redcker/scripts#5]
日志文件没有看到输出

**Comment by Redcker** [comment]
确定已经启动？ps看下进程

**Comment by aobama-mac** [comment]
> 确定已经启动？ps看下进程
看到进程,启动都生成cfd.log文件,就是里面空白命令cat 和xftp工具查看一样

**Comment by Redcker** [comment]
不要用nohup，直接python3执行脚本看有无报错

**Comment by aobama-mac** [comment]
`[root@xxxx-centos jd]# ps -aux | grep 'python3 jx_cfd_hb.py'
root      3235  0.0  0.0 115928  1020 pts/0    R+   22:51   0:00 grep --color=auto python3 jx_cfd_hb.py
[1]+  Exit 1                  python3 jx_cfd_hb.py > /dev/null 2>&1
[root@xxxx-centos jd]# cat cfd.log 
[root@xxxx-centos jd]# 
`

**Comment by aobama-mac** [comment]
> 不要用nohup，直接python3执行脚本看有无报错

`[root@VM-xxx-centos jd]# ps -aux | grep 'python3 jx_cfd_hb.py'
root      3235  0.0  0.0 115928  1020 pts/0    R+   22:51   0:00 grep --color=auto python3 jx_cfd_hb.py
[1]+  Exit 1                  python3 jx_cfd_hb.py > /dev/null 2>&1
[root@VM-xxx-centos jd]# cat cfd.log 
[root@VM-xxx-centos jd]# 
`

**Comment by Redcker** [comment]
日志文件是否有内容

>

**Comment by ShootTau** [comment]
那个青龙版的脚本好像有啥问题
有时候抢购结果：奖品正在补货中，请稍后再试~
Traceback (most recent call last):
  File "Redcker_scripts_qinglong_jx_cfd_hb.py", line 107, in <module>
    jx_cfd.exchange_red_package()
  File "Redcker_scripts_qinglong_jx_cfd_hb.py", line 84, in exchange_red_package
    delete_envs([advance_time['id']])
KeyError: 'id'

**Comment by ShootTau** [comment]
有时候又这样
Traceback (most recent call last):
  File "Redcker_scripts_qinglong_jx_cfd_hb.py", line 73, in exchange_red_package
    ret = self.session.get(cfd_url).json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Redcker_scripts_qinglong_jx_cfd_hb.py", line 107, in <module>
    jx_cfd.exchange_red_package()
  File "Redcker_scripts_qinglong_jx_cfd_hb.py", line 75, in exchange_red_package
    except requests.exceptions.JSONDecodeError:
AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'

**Comment by ShootTau** [comment]
青龙版本是2.9.3

**Comment by eadorothy86** [comment]
![图片](https://user-images.githubusercontent.com/85786428/156993872-5e0eddb6-2326-48ec-85e7-516072b9daa7.png)
启动了，ck报错？

**Comment by Redcker** [comment]
> 青龙版本是2.9.3

我的是2.11，尽量更新下面板，我晚上会出一个兼容版，注意关注最新push

**Comment by Redcker** [comment]
> ![图片](https://user-images.githubusercontent.com/85786428/156993872-5e0eddb6-2326-48ec-85e7-516072b9daa7.png) 启动了，ck报错？

拉取最新代码没？

**Comment by eadorothy86** [comment]
> > 青龙版本是2.9.3
> 
> 我的是2.11，尽量更新下面板，我晚上会出一个兼容版，注意关注最新push

我刚刚用2.10.12也是楼上出现的情况一样

**Comment by Redcker** [comment]
> > > 青龙版本是2.9.3
> > 
> > 
> > 我的是2.11，尽量更新下面板，我晚上会出一个兼容版，注意关注最新push
> 
> 我刚刚用2.10.12也是楼上出现的情况一样

看下你cookie的格式

**Comment by ShootTau** [comment]
2022-03-07 15:06:57,387 - 定时脚本启动成功
2022-03-07 16:01:52,960 - 定时脚本启动成功
2022-03-07 16:59:59,800 - 开始请求，当前时间为：2022-03-07 16:59:59:800010
2022-03-07 17:00:00,832 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
2022-03-07 17:59:59,193 - 开始请求，当前时间为：2022-03-07 17:59:59:193314
2022-03-07 18:00:00,222 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
2022-03-07 18:59:59,188 - 开始请求，当前时间为：2022-03-07 18:59:59:188489
2022-03-07 19:00:00,216 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
2022-03-07 19:59:06,486 - 定时脚本启动成功
2022-03-07 19:59:59,240 - 开始请求，当前时间为：2022-03-07 19:59:59:240313
2022-03-07 19:59:59,804 - 开始请求，当前时间为：2022-03-07 19:59:59:804122
2022-03-07 20:00:00,271 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
2022-03-07 20:00:00,842 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求

**Comment by Redcker** [comment]
> 2022-03-07 15:06:57,387 - 定时脚本启动成功 2022-03-07 16:01:52,960 - 定时脚本启动成功 2022-03-07 16:59:59,800 - 开始请求，当前时间为：2022-03-07 16:59:59:800010 2022-03-07 17:00:00,832 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求 2022-03-07 17:59:59,193 - 开始请求，当前时间为：2022-03-07 17:59:59:193314 2022-03-07 18:00:00,222 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求 2022-03-07 18:59:59,188 - 开始请求，当前时间为：2022-03-07 18:59:59:188489 2022-03-07 19:00:00,216 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求 2022-03-07 19:59:06,486 - 定时脚本启动成功 2022-03-07 19:59:59,240 - 开始请求，当前时间为：2022-03-07 19:59:59:240313 2022-03-07 19:59:59,804 - 开始请求，当前时间为：2022-03-07 19:59:59:804122 2022-03-07 20:00:00,271 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求 2022-03-07 20:00:00,842 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求

你这个要么是cookie无效要么格式不对

**Comment by ShootTau** [comment]
ck有效的 青龙还在跑脚本  格式填的是"pt_key=xxx"

**Comment by Redcker** [comment]
去财富岛看下是否能看到红包

**Comment by Redcker** [comment]
> ck有效的 青龙还在跑脚本 格式填的是"pt_key=xxx"

去财富岛看下是否能看到红包

**Comment by ShootTau** [comment]
有的

**Comment by Redcker** [comment]
给我邮箱发下你的ck，我看下具体问题

**Comment by Redcker** [comment]
> 有的

给我邮箱发下你的ck，我看下具体问题

**Comment by ShootTau** [comment]
我妖火站内信给你发
