### ISSUE TITLE
脚本运行出现错误信息，日志如下

### ISSUE THREAD

**Issue by 07031218** [Redcker/scripts#6]
Traceback (most recent call last):
  File "jx_cfd_hb.py", line 73, in exchange_red_package
    ret = self.session.get(cfd_url).json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jx_cfd_hb.py", line 104, in <module>
    jx_cfd.exchange_red_package()
  File "jx_cfd_hb.py", line 75, in exchange_red_package
    except requests.exceptions.JSONDecodeError:
AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'

**Comment by Redcker** [comment]
是最新代码么

**Comment by aobama-mac** [comment]
cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求

我的出现这个

> 是最新代码么

**Comment by Redcker** [comment]
如果是最新代码的话，请检查cookie是否有效以及格式是否正确

**Comment by aobama-mac** [comment]
> 如果是最新代码的话，请检查cookie是否有效以及格式是否正确

pt_key=xxxx;后面这个;需要?

**Comment by eadorothy86** [comment]
> cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
> 
> 我的出现这个
> 
> > 是最新代码么

2022-03-07 17:59:59,809 - 开始请求，当前时间为：2022-03-07 17:59:59:808949
2022-03-07 18:00:01,829 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
2022-03-07 18:59:59,227 - 开始请求，当前时间为：2022-03-07 18:59:59:227494
2022-03-07 18:59:59,327 - 抢购结果：奖品已经发完啦，下次早点来哦~
2022-03-07 19:59:59,225 - 开始请求，当前时间为：2022-03-07 19:59:59:225254
2022-03-07 19:59:59,333 - 抢购结果：奖品已经发完啦，下次早点来哦~
2022-03-07 20:59:59,211 - 开始请求，当前时间为：2022-03-07 20:59:59:211736
2022-03-07 20:59:59,299 - 抢购结果：奖品已经发完啦，下次早点来哦~
2022-03-07 21:59:59,294 - 开始请求，当前时间为：2022-03-07 21:59:59:294378
2022-03-07 22:00:00,341 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
2022-03-07 22:59:59,230 - 开始请求，当前时间为：2022-03-07 22:59:59:230103
2022-03-07 23:00:00,279 - cookie认证失败，请不要担心，这个是偶发情况。此次请求停止，等待下次请求
应该是正常的获取失败而已
