### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by qiange167** [Redcker/scripts#8]
2022-03-08 11:00:00,958 - Job "JxCFD.exchange_red_package (trigger: cron[minute='59', second='59'], next run at: 2022-03-08 11:59:59 CST)" raised an exception
Traceback (most recent call last):
  File "F:/Python/scripts-master/jd/jx_cfd_hb.py", line 85, in exchange_red_package
    ret = self.session.get(cfd_url).json()
  File "C:\Program Files\Python39\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "F:/Python/scripts-master/jd/jx_cfd_hb.py", line 88, in exchange_red_package
    except requests.exceptions.JSONDecodeError:
AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'

**Comment by Redcker** [comment]
cookie有效且填写正常吗

**Comment by qiange167** [comment]
又好了
